name: Node.js CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      id: run-tests
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
      run: npm test
      
    - name: Run tests with coverage
      id: run-tests-coverage
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: npm run test:coverage
      
    - name: Archive code coverage results
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage/
        
    - name: Send email notification on failure
      uses: dawidd6/action-send-mail@v3
      if: failure()
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: '❌ Jest Tests Failed: ${{ github.repository }}'
        body: |
          Tests have failed in repository ${{ github.repository }}
          
          Workflow: ${{ github.workflow }}
          Run: ${{ github.run_id }}
          Committer: ${{ github.actor }}
          Commit: ${{ github.sha }}
          
          See details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        to: ${{ secrets.EMAIL_TO }}
        from: GitHub Actions

    # Commented out Slack notification
    # - name: Send Slack notification on failure
    #   uses: 8398a7/action-slack@v3
    #   if: failure()
    #   with:
    #     status: ${{ job.status }}
    #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
    #     text: 'Test failures in ${{ github.repository }}'
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
